room/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.home_view, name='home'),
    path('browse/', views.PostList.as_view(), name='browse_rental'),    
    path('post_details/<int:post_id>/',views.post_detail, name='post_details'),
    path('post_details/<int:post_id>/edit_comment/<int:comment_id>',views.comment_edit, name='comment_edit'),
    path('post_details/<int:post_id>/delete_comment/<int:comment_id>/',views.comment_delete, name='comment_delete'),
    path('post_room/', views.post_room, name='post_room'),
    
]

student_marketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('summernote/', include('django_summernote.urls')),    
    path("", include("room.urls"), name="room-urls"),
]

room/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

class RoomPost(models.Model):
    """
        model for room post
    """
    title = models.CharField(unique=True)
    
    post_user = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        related_name = "room"
    )
    featured_image = CloudinaryField('image',default ='placeholder')
    description = models.TextField(null = True)
    updated_on = models.DateTimeField(auto_now =True)
    created_on = models.DateTimeField(auto_now=True)
    available_from = models.DateField()
    available_to = models.DateField()
    approved_on = models.BooleanField(default=False)

    # to do add method to change the dateField of availible to and from 

    def __str__(self):
        return f"The title of the post is {self.title}"

    class Meta:
        ordering = ["created_on",]
    
    def __str__(self):
        return f"{self.title}|post by {self.post_user}"

class Comment(models.Model):
    """
        model for room post's comments
    """
    post = models.ForeignKey(
        RoomPost,
        on_delete = models.CASCADE,
        related_name = "comments"
    )

    user = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        related_name = "commenter"
    )
    class Meta:
        ordering = ["-created_on",]

    def __str__(self):
        return f"Comment{self.user}"

    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True) 

room/forms.py
from django import forms
from .models import Comment, RoomPost


class RoomPostForm(forms.ModelForm):
    """
    Create post form
    """
    class Meta:
        model = RoomPost
        fields = ['title', 'post_user', 'featured_image', 'description', 'available_from', 'available_to']
        widgets = {
            'available_from': forms.DateInput(attrs={'type': 'date'}),
            'available_to': forms.DateInput(attrs={'type': 'date'}),
            'description': forms.Textarea(attrs={'rows': 5}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

room/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import RoomPost, Comment
from .forms import CommentForm, RoomPostForm



def home_view(request):
    """ Return the home page view """
    return render(request, 'room/index.html')


class PostList(generic.ListView):
    """
    Display the rooms post in list on index page
    """
    queryset = RoomPost.objects.filter (approved_on=1)
    template_name = "room/browse_rental.html"
    
def post_detail(request,post_id):
    """
    Display the blog in detail when click on the title or text below the title.
    """
    queryset = RoomPost.objects.all()
    post = get_object_or_404(queryset, id=post_id)
    comments = post.comments.all().order_by("created_on")
    comment_count = post.comments.filter(approved=True).count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and waiting for approval'
            )
    else: 
            comment_form = CommentForm()

    return render(
        request,
        "room/post_details.html",
        {   "post": post,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form
        }
    )


def comment_edit(request, post_id, comment_id):
    """
    Edit the single comment which have already submitted.
    """
    queryset = RoomPost.objects.all()
    post = get_object_or_404(queryset, id=post_id)
    comment = get_object_or_404(Comment, id=comment_id)
    comment_form = CommentForm(data=request.POST, instance=comment)

    if request.method == "POST":
        # return redirect('post_details', post_id= post.id)
        
        if comment_form.is_valid() and comment.user == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 
                                            'Comment has been Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error Updating Comments')

    return HttpResponseRedirect(reverse('post_details',args=[post_id]))
    # return render(request, 'room/post_details.html', {'comment': comment, 'post': post})


def comment_delete(request, post_id, comment_id):
    """
    Delete the single Comment from Comment List
    """
    queryset = RoomPost.objects.all()
    post = get_object_or_404(queryset,id= post_id)
    comment = get_object_or_404(Comment, id= comment_id)


    if comment.user == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment has deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse("post_details",args=[post_id]))


# def post_room(request, post_id):
#     post = get_object_or_404(RoomPost, id=post_id)
#     if request.method == 'POST':
#         form = RoomPostForm(request.POST, request.FILES)
#         if form.is_valid():
#             room_post = form.save(commit=False)
#             room_post.post_user = request.user
#             room_post.save()           
#             return redirect('post_details', post_id=post.id)
#     else:
#         form = RoomPostForm()

#     return render(request, 'room/post_room.html', {'form': form})

def post_room(request, post_id=None):
    if post_id:
        post = get_object_or_404(RoomPost, id=post_id)
    else:
        post = None
    
    if request.method == 'POST':
        form = RoomPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            room_post = form.save(commit=False)
            room_post.post_user = request.user
            room_post.save()
            return redirect('post_details', post_id=room_post.id)
    else:
        form = RoomPostForm(instance=post)
    
    return render(request, 'room/post_room.html', {'form': form})

room/templates/room/browse_rental.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid">
    {% for roompost in roompost_list %}
        <div class="mx-auto browsepost_body row">
            <div class="col">
                <a href="{% url 'post_details' roompost.id %}">
                {% if "placeholder" in roompost.featured_image.url %}
                <img class="placeholder" src="{% static 'images/default.jpg' %}" 
                    alt="placeholder image">
                {% else %}
                <img class="placeholder" src="{{ roompost.featured_image.url}}" 
                    alt="{{roompost.title}}">
                {% endif %}
                </a>
            </div>
            <div class="col">
                <article>
                    <h1 class=""><a href="{% url 'post_details' roompost.id %}">  {{roompost.title}} </a></h1>
                    <p class=""> {{roompost.description | safe }} </p>
                    <p> Date Available From : {{roompost.available_from }}</p>
                    <p> Date Available To : {{roompost.available_to }}</p>
                </article>
            </div>     
        </div>
    {% endfor %}
</div>
{% endblock content%}

room/templates/room/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<!-- Background image -->
<div class="hero-image"
    style="background-image: url('/static/images/hero.jpg'); background-position: center; background-size: cover">

    <!-- Centered text and button -->
    <div class="hero-text text-center" style="position: absolute; background-color: #e6e4e481;">
        <h1>Find your perfect student room at Campus Corner!</h1>
        {% if user.is_authenticated %}
        <a href="{% url 'browse_rental' %}" class="btn btn-light">Browse Post!</a>
        {% else %}
        <a href="{% url 'account_signup' %}" class="btn btn-light">Sign up!</a>
        {% endif %}
    </div>
</div>

<!-- What we do section -->
<div class="container mt-5 d-sm-block">
    <div class="row">
        <div class="col-md-6 text-center">
            <h2 class="text-center mb-4"><i class="fa-solid fa-building-columns"></i> What we do</h2>
            <p>Campus Corner is a platform that connects students looking for affordable accommodation
                with those who have available rooms to rent. The website provides an easy and convenient way for
                users
                to post listings, search for shared housing, and find compatible roommates. From shared rooms to
                private
                spaces, we help students create their ideal living arrangements. We are a dedicated platform
                designed to
                make student housing simple and stress-free.
            </p>
        </div>

        <div class="col-md-6 text-center">
            <h2 class="text-center mb-4"><i class="fa-solid fa-house-user"></i> Host with Us</h2>
            <p>Looking to rent out a room and connect with fellow students? Hosting with us is simple, efficient,
                and secure.
                By listing your room on our platform, you'll be able to reach a broad community of students
                searching for
                accommodation. Whether you have a spare room in your apartment or an entire unit to offer, our
                platform makes
                it easy to post, manage, and communicate with potential roommates. Join our network today and let us
                help you
                find the perfect tenant for your space!
            </p>
        </div>
    </div>
</div>


{% endblock %}

room/templates/room/post_details.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

  <div class="container postDetails_body mx-auto">
    <div class="row">
       <!-- Post title goes in these h1 tags -->
      <h1 class="text-center">{{ post.title }}</h1>
      <p class="text-center">{{ post.user }} | {{ post.created_on }}</p>
    </div>
    <div class="row">
      <div class="col-md-6 masthead-text">
        {% if "placeholder" in post.featured_image.url %}
        <img class="placeholder" src="{% static 'images/default.jpg' %}" alt="placeholder image">
        {% else %}
        <img class="placeholder" src="{{ post.featured_image.url}}" alt="{{roompost.title}}">
        {% endif %}
      </div>
    
      <div class="col card mb-4  mt-3">
          <article>{{ post.description | safe }}</article>
      </div>
    </div>
      
      <!-- Displaying count of comments -->
      <div class="row">
        <div class="col-12">
          <strong class="">
            <i class="far fa-comments"></i> {{ comment_count }}
          </strong>
        </div>
        <div class="col-12">
          <hr>
        </div>
      </div>

      <!-- Displaying Comments -->
      <div class="row">
        <div class="col-md-6 card mb-6  mt-3">
          <h3>Comments:</h3>
          <div class="card-body">
            {% for comment in comments %}
            <div class="p-2 comments" {% if not comment.approved and comment.user == user %} faded
              {% elif not comment.approved %} d-none{% endif %}>
              <p class="font-weight-bold">
                {{ comment.user }}
                {{ comment.created_on }}
                wrote:
              </p>
              <div id="comment{{ comment.id }}">
                {{ comment.body }}
              </div>
              {% if not comment.approved and comment.user == user %}
              <p class="approval">This comment is awaiting approval</p>
              {%endif%}
              {% if user.is_authenticated and comment.user == user %}
              <button class="btn btn-delete" data-post-id="{{post.id}}"
                data-comment_id="{{ comment.id }}">Delete</button>
              <button class="btn btn-edit" data-post-id="{{post.id}}" data-comment_id="{{ comment.id }}">Edit</button>
              {%endif%}
            </div>
            <!-- Our for loop ends here -->
            {% endfor %}
          </div>
        </div>


        <!-- Creating New Comments -->
        <div class="col-md-6 card mb-4 mt-3">
          <div class="card-body">
            {% if user.is_authenticated %}
            <h3>Leave a comment:</h3>
            <p>Posting as: {{ user.username }}</p>
            <form id="commentForm" method="post" style="margin-top: 1.3em;">
              {{ comment_form | crispy }}
              {% csrf_token %}
              <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
            </form>
            {% else %}
            <p>Log in to leave a comment</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <!-- Delete confirmation modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Are you sure you want to delete your comment?
            This action cannot be undone.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <a id="deleteConfirm" href="#" class="btn
        btn-danger">Delete</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

  {% block extras %}
  <script src="{% static 'JS/comments.js' %}"></script>
  {% endblock %}

room/templates/room/post_room.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Page title -->
<div class="container">
    <h1 class="text-center" style="padding-top: 50px; padding-bottom: 30px;">Create New Post</h1>
    <div class="row justify-content-center">
        {% if user.is_authenticated %}
            {% load cloudinary %}
            <div class="col-10 col-md-8 col-lg-4 mt-3">
                <!--  Add Post Room Form -->
                <form method="POST" enctype="multipart/form-data" action="{% url 'post_room' %}">                        
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Campus Corner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/png" href="{& static 'images/' &}">

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">

            <a class="navbar-brand" href="{% url 'home' %}">
                <img class="logo" src="{% static 'images/logo.png' %}" alt="Campus Corner">
            </a>

            <button class="navbar-dark navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_url %}active" aria-current="page{% endif %}"
                            href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item"></li>
                    <a class="nav-link {% if request.path == browse_rental %}active" aria-current="page{% endif %}"
                        href="{% url 'browse_rental' %}">Browse Post</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"></li>
                    <a class="nav-link {% if request.path == post_room %}active" aria-current="page{% endif %}"
                        href="{% url 'post_room' %}">Add Post</a>
                    </li>
                    <li class="nav-item"></li>
                    <a class="nav-link {% if request.path == account_logout %}active" aria-current="page{% endif %}"
                        href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item"></li>
                    <a class="nav-link {% if request.path == account_signup %}active" aria-current="page{% endif %}"
                        href="{% url 'account_signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == account_login %}active{% endif %}" aria-current="page"
                            href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <div class="flex-shrink-0">
                    {% if user.is_authenticated %}
                    <p class="text-end m-3">You are logged in as {{ user }}</p>
                    {% else %}
                    <p class="text-end m-3">You are not logged in</p>
                    {% endif %}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
    </nav>
    <main>
        {% block content %}

        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3">
        <p class="m-0 text-center text-white"></p>
        {% block copyright %}
        Copyright: Team Coffee Overflow
        {% endblock copyright %}
        </p>
        <p class="m-0 text-center text-white"> Follow us:
            <a href="https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F%3Flocale%3Den_GB"
                target="_blank" rel="noopener" aria-label="Go to my Facebook Account" style="color: #fff;"><i
                    class="fab fa-facebook-square ms-3 link-text"></i></a>
            <a href="https://x.com/?lang=en" target="_blank" rel="noopener" aria-label="Go to my Twitter Account" style="color: #fff;"><i
                    class="fab fa-twitter-square ms-3 link-text" ></i></a>
            <a href="https://www.instagram.com/accounts/login/" target="_blank" rel="noopener"
                aria-label="Go to my Instagram Account" style="color: #fff;"><i class="fab fa-instagram-square ms-3 link-text"></i></a>
            <a href="https://www.youtube.com/" target="_blank" rel="noopener" aria-label="Go to my Youtube Account" style="color: #fff;"><i
                    class="fab fa-youtube-square ms-3 link-text"></i></a>
        </p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    {% block extras %}
    {% endblock %}
</body>

</html>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}